# Generated by Django 3.1.3 on 2020-11-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201126_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Foto'),
        ),
    ]
